# Generated by Django 4.2.7 on 2024-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_photo',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to='items_media/'),
        ),
    ]
