# Generated by Django 4.2.7 on 2024-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0002_remove_cart_items_remove_cart_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_status',
            field=models.BooleanField(default=True),
        ),
    ]
