# Generated by Django 4.2.7 on 2024-02-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0003_storeitems_created_storeitems_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
