# Generated by Django 4.2.7 on 2024-02-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0006_size_remove_storeitems_item_size_itemsize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitems',
            old_name='sizes',
            new_name='item_size',
        ),
    ]
