# Generated by Django 4.2.7 on 2024-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0007_rename_sizes_storeitems_item_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitems',
            name='item_size',
        ),
        migrations.AddField(
            model_name='storeitems',
            name='sizes',
            field=models.ManyToManyField(through='TheApp.ItemSize', to='TheApp.size'),
        ),
    ]
