# Generated by Django 5.0.2 on 2024-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0008_remove_storeitems_item_size_storeitems_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='price_increase_percentage',
            field=models.IntegerField(default=None),
        ),
    ]
