# Generated by Django 5.0.2 on 2024-03-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0009_alter_itemsize_price_increase_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='price_increase_percentage',
            field=models.BigIntegerField(default=None),
        ),
    ]
