# Generated by Django 5.0.2 on 2024-03-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0010_alter_itemsize_price_increase_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_value', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='storeitems',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('AC', 'Active'), ('IN', 'Inactive')], default='DR', max_length=2),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='items_videos/'),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='primary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_color_items', to='TheApp.color'),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='secondary_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_color_items', to='TheApp.color'),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items_media/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheApp.storeitems')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('items', models.ManyToManyField(related_name='sections', to='TheApp.storeitems')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('P', 'Percentage'), ('F', 'Fixed Amount')], max_length=1)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TheApp.storeitems')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TheApp.sections')),
            ],
        ),
        migrations.AddField(
            model_name='storeitems',
            name='tags',
            field=models.ManyToManyField(blank=True, to='TheApp.tags'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('choices', models.TextField(help_text='Enter variations separated by commas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheApp.storeitems')),
            ],
        ),
    ]
