# Generated by Django 5.0.2 on 2024-03-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0011_color_tags_storeitems_height_storeitems_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('items', models.ManyToManyField(related_name='section', to='TheApp.storeitems')),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TheApp.section'),
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
    ]
