# Generated by Django 5.0.2 on 2024-03-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0012_rename_tags_tag_section_alter_discount_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='variations',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TheApp.variation'),
        ),
    ]
