# Generated by Django 5.0.2 on 2024-03-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0013_storeitems_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitems',
            name='variations',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TheApp.variation'),
        ),
    ]
