# Generated by Django 5.0.2 on 2024-03-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0014_alter_storeitems_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitems',
            name='variations',
        ),
    ]
