# Generated by Django 5.0.2 on 2024-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0017_remove_variation_choices_remove_variation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='choices',
            field=models.TextField(default=True, help_text='Enter variations separated by commas'),
        ),
    ]
