# Generated by Django 5.0.2 on 2024-03-09 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0018_variation_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='item',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='TheApp.storeitems'),
        ),
    ]
