# Generated by Django 5.0.2 on 2024-03-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0019_variation_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='item',
        ),
    ]
