# Generated by Django 5.0.2 on 2024-03-09 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0020_remove_variation_choices_remove_variation_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('item_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='TheApp.itemvariation')),
            ],
        ),
    ]
