# Generated by Django 5.0.2 on 2024-05-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0021_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='variants',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
