# Generated by Django 5.0.2 on 2024-05-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0023_alter_variation_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variants',
            field=models.CharField(max_length=200),
        ),
    ]
