# Generated by Django 5.0.2 on 2024-05-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0024_alter_variation_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='variants',
        ),
    ]
