# Generated by Django 5.0.2 on 2024-05-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0025_remove_variation_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='variant',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
