# Generated by Django 5.0.2 on 2024-05-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0026_itemvariation_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_increment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='TheApp.variation')),
            ],
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TheApp.choices'),
        ),
    ]
