# Generated by Django 5.0.2 on 2024-05-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0027_choices_itemvariation_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='itemvariation',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='itemvariation',
            name='variant',
        ),
        migrations.CreateModel(
            name='Variation_Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_increment', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='TheApp.variation')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
    ]
