# Generated by Django 5.0.2 on 2024-05-17 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0028_remove_choices_variation_remove_itemvariation_choice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation_Choice',
            new_name='Choices',
        ),
        migrations.RemoveField(
            model_name='storeitems',
            name='variations',
        ),
        migrations.AlterField(
            model_name='choices',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='TheApp.itemvariation'),
        ),
    ]
