# Generated by Django 5.0.2 on 2024-05-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0029_rename_variation_choice_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariation',
            name='variation_price',
        ),
    ]
