# Generated by Django 5.0.2 on 2024-05-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0030_remove_itemvariation_variation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitems',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='ItemSize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
