# Generated by Django 5.0.2 on 2024-05-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0031_remove_storeitems_sizes_delete_itemsize_delete_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='variations',
            field=models.ManyToManyField(through='TheApp.ItemVariation', to='TheApp.variation'),
        ),
    ]
