# Generated by Django 5.0.2 on 2024-05-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0033_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='TheApp.section'),
        ),
    ]
