# Generated by Django 5.0.2 on 2024-05-27 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0041_alter_storeitems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='section', to='TheApp.storeitems'),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items_category', to='TheApp.section'),
        ),
    ]
