# Generated by Django 5.0.2 on 2024-05-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0042_alter_section_items_alter_storeitems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='section', to='TheApp.storeitems'),
        ),
    ]
