# Generated by Django 5.0.2 on 2024-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0043_alter_section_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitems',
            name='category',
        ),
        migrations.AddField(
            model_name='storeitems',
            name='category',
            field=models.ManyToManyField(default=None, related_name='items_category', to='TheApp.section'),
        ),
    ]
