# Generated by Django 5.0.2 on 2024-05-27 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0044_remove_storeitems_category_storeitems_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='items',
        ),
        migrations.AddField(
            model_name='section',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='TheApp.storeitems'),
        ),
    ]
