# Generated by Django 5.0.2 on 2024-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0048_section_items_storeitems_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitems',
            name='category',
        ),
        migrations.AddField(
            model_name='storeitems',
            name='category',
            field=models.ManyToManyField(related_name='category_items', to='TheApp.section'),
        ),
    ]
