# Generated by Django 5.0.2 on 2024-05-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0049_remove_storeitems_category_storeitems_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitems',
            name='category',
        ),
        migrations.AlterField(
            model_name='section',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='sections', to='TheApp.storeitems'),
        ),
    ]
