# Generated by Django 5.0.2 on 2024-06-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0050_remove_storeitems_category_alter_section_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='section', to='TheApp.storeitems'),
        ),
    ]
