# Generated by Django 5.0.2 on 2024-06-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0052_rename_itemimage_storeitemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='price_increase_percentage',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='choices',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Choices', to='TheApp.choices'),
        ),
    ]
