# Generated by Django 5.0.2 on 2024-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0055_remove_choices_price_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='choices',
            field=models.ManyToManyField(blank=True, to='TheApp.choices'),
        ),
    ]
