# Generated by Django 5.0.2 on 2024-06-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0057_remove_storeitems_choices_choices_price_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitems',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
