# Generated by Django 5.0.2 on 2024-06-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0059_alter_storeitems_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='price_increment',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
