# Generated by Django 5.0.2 on 2024-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0060_alter_choices_price_increment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='item_variations',
            field=models.ManyToManyField(blank=True, to='TheApp.itemvariation'),
        ),
    ]
