# Generated by Django 5.0.2 on 2024-10-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0061_storeitems_item_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TheApp.storeitems'),
        ),
        migrations.AlterField(
            model_name='storeitems',
            name='item_variations',
            field=models.ManyToManyField(blank=True, default=True, to='TheApp.itemvariation'),
        ),
    ]
