# Generated by Django 5.0.2 on 2024-10-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0065_remove_choices_store_item_choices_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='item',
        ),
        migrations.RemoveField(
            model_name='storeitems',
            name='item_choices',
        ),
    ]
