# Generated by Django 5.0.2 on 2024-10-05 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0066_remove_choices_item_remove_storeitems_item_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TheApp.storeitems'),
        ),
        migrations.AddField(
            model_name='storeitems',
            name='item_choices',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Choices'),
        ),
    ]
