# Generated by Django 5.0.2 on 2024-10-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0067_choices_item_storeitems_item_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='item',
        ),
        migrations.RemoveField(
            model_name='storeitems',
            name='item_choices',
        ),
    ]
