# Generated by Django 5.0.2 on 2024-10-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0068_remove_choices_item_remove_storeitems_item_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
