# Generated by Django 5.0.2 on 2024-10-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0069_choices_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='visible',
        ),
    ]
