# Generated by Django 5.0.2 on 2024-11-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0070_remove_choices_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitems',
            options={'verbose_name_plural': 'Store Items'},
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='variation',
            new_name='item_variation',
        ),
        migrations.AlterField(
            model_name='choices',
            name='price_increment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
