# Generated by Django 5.0.2 on 2024-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0072_alter_choices_price_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='price_increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
