# Generated by Django 5.0.2 on 2024-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0073_alter_choices_price_increment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvariation',
            options={'verbose_name_plural': 'Item Variations'},
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='item_variation',
            new_name='variation',
        ),
        migrations.AlterField(
            model_name='choices',
            name='price_increment',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
