# Generated by Django 5.0.2 on 2024-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0078_storeitemimage_created_at_alter_storeitemimage_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
