# Generated by Django 5.0.2 on 2024-12-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0079_storeitems_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitems',
            name='discount_percentage',
        ),
    ]
