# Generated by Django 5.0.2 on 2025-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0080_remove_storeitems_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
