# Generated by Django 5.0.2 on 2025-03-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0081_storeitems_discounted_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeitems',
            options={},
        ),
        migrations.RemoveField(
            model_name='storeitems',
            name='discounted_price',
        ),
    ]
