# Generated by Django 5.0.2 on 2025-04-10 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0084_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='facebook_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='instagram_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='twitter_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artist_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
