# Generated by Django 5.2.10 on 2026-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0085_artistprofile_facebook_show_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.CharField(choices=[('OR', 'Originals'), ('PR', 'Prints')], default='OR', max_length=2),
        ),
    ]
