# Generated by Django 5.2.10 on 2026-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0086_section_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitems',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('AC', 'Active'), ('IN', 'Inactive'), ('SC', 'ShowCase'), ('SO', 'Sold')], default='DR', max_length=2),
        ),
    ]
