# Generated by Django 5.2.10 on 2026-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0087_alter_storeitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitems',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
