# Generated by Django 4.2.7 on 2024-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitems',
            name='item_photo',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to='items_media/'),
        ),
    ]
