# Generated by Django 5.0.2 on 2024-06-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='storeitem',
            new_name='product',
        ),
    ]
