# Generated by Django 5.0.2 on 2024-06-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_storeitem_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='storeitem',
        ),
    ]
