# Generated by Django 5.0.2 on 2025-03-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_choice_increment_orderitem_choice_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='choice_increment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
