# Generated by Django 5.0.2 on 2025-03-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_choice_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='choice_increment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
