# Generated by Django 5.0.2 on 2025-04-22 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_choice_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='choice_increment',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='choice_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variation_name',
        ),
        migrations.CreateModel(
            name='OrderItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(blank=True, max_length=100, null=True)),
                ('choice_name', models.CharField(blank=True, max_length=100, null=True)),
                ('choice_increment', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='orders.orderitem')),
            ],
        ),
    ]
