# Generated by Django 5.0.2 on 2025-04-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_orderitem_choice_increment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='choice_increment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='choice_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='OrderItemVariation',
        ),
    ]
