# Generated by Django 5.0.2 on 2025-04-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderitem_choice_increment_orderitem_choice_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='choice_increment',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='choice_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variation_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
