# Generated by Django 5.0.2 on 2025-04-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_orderitem_choice_increment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
